# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZUEUHvmKefPIHPqots4tCkvLT2VMnbBK
"""

pip install streamlit openpyxl

import streamlit as st
from datetime import datetime, timedelta
import pandas as pd
from io import BytesIO

# Function to calculate next Monday
def get_next_monday(date):
    order_dt = datetime.strptime(date, "%Y/%m/%d")
    days_ahead = 0 - order_dt.weekday() + 7
    if days_ahead <= 0:
        days_ahead += 7
    return order_dt + timedelta(days=days_ahead)

# Title of the web app
st.title("📦 Order Processing App")

# User inputs
st.header("🔖 Order Information")
ref_no = st.text_input("Order Ref Number")
client_name_jp = st.text_input("Client Name (JP)")
client_name_en = st.text_input("Client Name (EN)")
order_date = st.text_input("Order Date (YYYY/MM/DD)")
qty = st.number_input("Quantity Ordered", min_value=1, step=1)
total_usd = st.number_input("Total Price (USD)", min_value=0.0, step=0.01)
tel_no = st.text_input("Telephone Number")
bar_code = st.text_input("Barcode")

if st.button("Generate Excel"):
    shipping_date = get_next_monday(order_date).strftime("%Y/%m/%d")

    # Cooling cubes calculation
    cooling_cubes = 4 if qty <= 50 else 6

    # Box determination
    if qty <= 20:
        box_type = "A"
    elif 21 <= qty <= 60:
        box_type = "B"
    else:
        box_type = "D"

    # Weight calculation data
    weights = {"babyderm": 11, "cooling_cube": 200, "A": 549, "B": 740, "D": 1172}
    buffer_stuff_weight = {"A": 200, "B": 300, "D": 500}

    net_weight = qty * weights["babyderm"]
    total_weight = net_weight + (cooling_cubes * weights["cooling_cube"]) + weights[box_type] + buffer_stuff_weight[box_type]

    # Excel generation
    excel_data = {
        "備註": [bar_code],
        "訂單編號": [ref_no],
        "箱子種類": [box_type],
        "保冷劑數量": [cooling_cubes],
        "通路": ["H"],
        "拋檔日": [order_date],
        "契客別": ["久泰開發股份有限公司"],
        "收件人": ["台灣雅瑪多國際物流股份有限公司華儲倉儲 梁孝宗/張建華"],
        "配送地址": ["337桃園市大園區航勤北路10-1號"],
        "TEL_NO": [tel_no],
        "付款名稱（1：不收款2：代收貨款）": [1],
        "配送時段（1：13點前2：13:00-17:003：不指定）": [1],
        "品號": ["3JS00005"],
        "品名": ["BABYDERM-50"],
        "銷貨數量": [qty],
        "配送日": [shipping_date]
    }

    df = pd.DataFrame(excel_data)

    # Prepare Excel for download
    output = BytesIO()
    with pd.ExcelWriter(output, engine='openpyxl') as writer:
        df.to_excel(writer, index=False)
    output.seek(0)

    # Provide download link
    st.success("✅ Excel Generated Successfully!")
    st.download_button(
        label="📥 Download Excel",
        data=output,
        file_name='domestic_shipping.xlsx',
        mime='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'
    )